### ISSUE TITLE
Set current repo as Env var 

### ISSUE THREAD

**Issue by carusooo** [gruntwork-io/git-xargs#115]
**Describe the solution you'd like**
Set the current repo as an environment variable that can be accessed while processing. From the logs it looks like this is available at invocation time
```
[git-xargs] DEBU[2023-03-03T10:38:56-08:00] Created branch                                Branch Name=refs/heads/add-self-hosted Repo=my-cool-repo
[git-xargs] DEBU[2023-03-03T10:38:56-08:00]                                               Repo=my-cool-repo
```

**Describe alternatives you've considered**
I could parse this out of the `cwd`, but that seems brittle since there's a lot of nonces to prevent collisions
```
/private/var/folders/zc/ysm6hx_n2qng1h09htfdw_8m0000gn/T/git-xargs-my-cool-repo1360847715
```
I could also invoke a git command and poke at the output, that involves too much shell cruft and line noise.

**Additional context**

It's possible this is already implemented or could be solved simpler than I envision.

**Comment by andyfeller** [comment]
I would like to expand upon @carusooo's idea _(hello, fellow Andy 👋)_ by also exposing `--dry-run` flag as environment variable, too.  This is essential in order to build safe processes beyond changing content to know whether to affect change or not.

<details><summary><b><code>git-xargs --help</code> usage statement</b></summary>
<p>

```shell
$ git-xargs.exe --help
Usage: git-xargs.exe [--loglevel] [--github-org] [--draft] [--dry-run] [--skip-pull-requests] [--skip-archived-repos]
[--repo] [--repos] [--branch-name] [--base-branch-name] [--commit-message] [--pull-request-title]
[--pull-request-description] [--reviewers] [--team-reviewers] [--seconds-between-prs] [--max-pr-retries]
[--seconds-to-wait-when-rate-limited] [--no-skip-ci] [--keep-cloned-repositories] [--help] command [options] [args]

git-xargs is a command-line tool (CLI) for making updates across multiple Github repositories with a single command.

Commands:

   help, h  Shows a list of commands or help for one command
```

</p>
</details>

**Comment by andyfeller** [comment]
@carusooo : check out https://github.com/gruntwork-io/git-xargs/pull/127 :fishsticks:
