### ISSUE TITLE
Binaries not included in assets for latest release (v0.1.4)

### ISSUE THREAD

**Issue by Syriiin** [gruntwork-io/git-xargs#116]
Title pretty much says it all.
Binaries haven't been included in the assets for the [v0.1.4 release](https://github.com/gruntwork-io/git-xargs/releases/tag/v0.1.4).

**Comment by eak12913** [comment]
Hey @Syriiin - Thanks for letting us know. I've corrected the issues we were having in our CI/CD pipeline but was not able to salvage the `v0.1.4` release. Instead I deleted `v0.1.4` and instead released `v0.1.5` which contains exactly the same. Please use this instead.
