### ISSUE TITLE
Rate limiting for repository cloning?

### ISSUE THREAD

**Issue by jpage-godaddy** [gruntwork-io/git-xargs#139]
**Describe the solution you'd like**
The ability to rate limit repository cloning operations

**Describe alternatives you've considered**
None

**Additional context**
I'm attempting to do a bulk operation on an org containing 176 repositories, but github is resetting the connection on all these clone operation attempts. It appears that the cloning is all being done in parallel, and my guess is that it's rate limiting operations. I see there's rate limiting on creating pull requests; perhaps applying a similar solution for the cloning operations would allow things to complete. Currently the operations are just failing without retries.

**Comment by flinn** [comment]
Bumping this, is there anything we can do towards helping to get [this PR merged](https://github.com/gruntwork-io/git-xargs/pull/142)? I'm happy to alter the README files with the documentation if that'd help move this along.
