### ISSUE TITLE
Add reviewers to pull request

### ISSUE THREAD

**Issue by radicarl** [gruntwork-io/git-xargs#15]
It would be great if I could add reviewers (teams and single persons) to the pull request git-xargs opens.
This way my reviewers will automatically see their pull requests.

https://docs.github.com/en/rest/reference/pulls#request-reviewers-for-a-pull-request

**Comment by zackproser** [comment]
@radicarl This is a great idea. Thanks for the suggestion. I'll look into it.

**Comment by Benjie-legit** [comment]
This is a great feature request

**Comment by zackproser** [comment]
Agree - this certainly makes sense to me as a feature to add. PRs to add this functionality in are very welcome, as we're pretty buried right now.

**Comment by zackproser** [comment]
@radicarl Give it a shot and let me know how it works!

**Comment by radicarl** [comment]
Tried the -team-reviewers option on internal repos and it worked like a charm.
Thank you.
