### ISSUE TITLE
Feature Request - option flag with  "--filter=blob:none" to clone repo

### ISSUE THREAD

**Issue by yanhong-tech** [gruntwork-io/git-xargs#152]
**Describe the solution you'd like**

When we clone the repo, repo has the `fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack:invalid index-pack output` error. 
So our solution for the reposition clone is `git clone --filter=blob:none <url>` [refer to here ](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/)

Now when using this **git-xargs** tool, the step clone the repo failure with 
```
Error cloning repository 
Error encountered while processing repo "unexpected EOF"
```
so can we have this flag `--filter=blob:none` add for git options to clone the repo? 

Thanks!

**Comment by autero1** [comment]
Looks like `go-git` doesn't support that for now: https://github.com/go-git/go-git/issues/713
