### ISSUE TITLE
Feature Request: Consider moving git clone progress from stdout to logger

### ISSUE THREAD

**Issue by jphuynh** [gruntwork-io/git-xargs#36]
**Is your feature request related to a problem? Please describe.**

I run git-xargs on a list of 500+ repositories and also from Github Actions. Running it on that scale logs a lot of information when cloning repositories. 

For example:

>Compressing objects: 100% (39/39)
Compressing objects: 100% (39/39), done.
Total 59 (delta 21), reused 35 (delta 12), pack-reused 0
Enumerating objects: 20, done.
Counting objects:  20% (1/5)
Counting objects:  40% (2/5)
Counting objects:  60% (3/5)
Counting objects:  80% (4/5)
Counting objects: 100% (5/5)
Counting objects: 100% (5/5), done.
Compressing objects:  33% (1/3)
Compressing objects:  66% (2/3)
Compressing objects: 100% (3/3)
Compressing objects: 100% (3/3), done.
Total 20 (delta 0), reused 0 (delta 0), pack-reused 15
Enumerating objects: 835, done.
Counting objects:   0% (1/111)
Counting objects:   1% (2/111)
Counting objects:   2% (3/111)
Counting objects:   3% (4/111) 

**Describe the solution you'd like**

Would it be possible to move that information to a debug log for example or add a `--quiet` option? (I think the former solution is preferable because `--quiet` would have a much bigger scope for the tool in general.)

**Describe alternatives you've considered**

Send progress to the logger instead of stdout https://github.com/gruntwork-io/git-xargs/blob/0fcd89a2e1a7594b20406468d746d72c0f7117f1/repository/repo-operations.go#L46

**Additional context**
N/A

**Comment by zackproser** [comment]
@jphuynh pretty sure you just fixed this so I'm going to close it out! Thanks again.
