### ISSUE TITLE
Homebrew suport

### ISSUE THREAD

**Issue by estahn** [gruntwork-io/git-xargs#43]
**Is your feature request related to a problem? Please describe.**

Simple install experience via `brew install git-xargs`.

**Describe the solution you'd like**

Using [goreleaser](https://github.com/goreleaser/goreleaser) this should be easy to configure.

Example: https://github.com/estahn/cloudping/blob/master/.goreleaser.yml

**Comment by chenrui333** [comment]
@estahn now you should be able to install with `brew install git-xargs`

**Comment by estahn** [comment]
> @estahn now you should be able to install with `brew install git-xargs`

Great, much appreciated. It worked!

**Comment by brikis98** [comment]
Ah, lovely, thank you @chenrui333!

**Comment by chenrui333** [comment]
@brikis98 my pleasure :)
